### PR TITLE
Require requests >= 2.4

### PR DESCRIPTION
**Pull request by fd0**
This is already in the code in `linkcheck/__init__.py`, update the requirements and setup file so it can be installed via `pip`.

### CODE REVIEW

**Comment by anarcat** [comment]
and yes, this is a mess, sorry!

**Comment by fd0** [comment]
It fails when installed via pip on Ubuntu Trusty (that's what Travis uses):

 * pip does not install requests, it's already installed: https://travis-ci.org/restic/restic.net/builds/366213777#L541
 * but running `linkchecker` fails: https://travis-ci.org/restic/restic.net/builds/366213777#L581

**Comment by anarcat** [comment]
right okay. i took the liberty of editing your branch to restore the other limit, could you test the result and see if it works for you?

**Comment by fd0** [comment]
Sure

**Comment by fd0** [comment]
Seems to work, pip installs a newer version of requests :)

**Comment by anarcat** [comment]
awesome, LGTM then.. :) glad to see you use linkchecker and thanks for the contribution!

**Comment by anarcat** [comment]
( @mgedmin it would be nice to cleanup those requirements and specify them just in one place... do you have a quick trick up your sleeves on how to do that? i always wonder why we need the .txt file in the first place...)

**Comment by fd0** [comment]
Cool, I like linkchecker, it does what it should. But I spent two hours fighting the old Python 2.7 (without SNI support *sad*) on Travis on Ubuntu Trusty. That was not fun at all :( (not your fault though, thanks for your work!)

**Comment by anarcat** [comment]
yeah, this thing is really showing its age. this is only what you see as a user, as a developer there are much worse horrors lurking below, e.g. #119

**Comment by fd0** [comment]
WTF? There's an HTML parser in this project? Written in **C**? Oh well. That was... unexpected...

**Comment by mgedmin** [comment]
TBH I think `requirements.txt` is not necessary for us and can be safely deleted.

It is currently used in tox.ini (redundant, except for the 'argcomplete' dependency that tox wouldn't otherwise pick up as it's missing from install_requires), and mentioned in a couple of files in `doc/`.

**Comment by anarcat** [comment]
@mgedmin let's remove it then, do you mind filing a pr?

**Comment by mgedmin** [comment]
Then I would have to come up with documentation updates...  I don't have the energy for that at the moment. :(

**Pull request merged**
