### PR TITLE
replace old links on website

### PR DESCRIPTION
**Pull request by anarcat**
point to the new orga at least while we figure out namespace issues

not sure this is the right way of doing this - i just did the search/replace here and did not regenerate the site from source.

Closes: #112

### CODE REVIEW

**Comment by anarcat** [comment]
this only changes the website, the source change is in #143.

**Comment by anarcat** [comment]
i think this branch is published on http://linkcheck.github.io/linkchecker/ but i must admit i have no clue how the hell this works.

http://linkcheck.github.io, i think, would be a separate repo under the linkcheck organization, named `linkcheck.github.io`. we don't have that, which is why it's a 404. if anything, we should have a blank site there there redirects to the website...

**Comment by mgedmin** [comment]
Ah, yes, that makes sense.

**Comment by mgedmin** [comment]
Sorry hit the wrong button

**Pull request merged**
