### PR TITLE
workaround new limitation in requests

### PR DESCRIPTION
**Pull request by anarcat**
newer requests do not expose the internal SSL socket object so we
cannot verify certificates. there was work to allow custom
verification routines which we could use, but this never finished:

https://github.com/shazow/urllib3/pull/257

so right now, just treat missing socket information as if the cert was
missing.

Closes: #76

### CODE REVIEW

**Comment by anarcat** [comment]
note that this would introduce a regression whereas we cannot verify SSL expiry times with newer requests versions. i'm not sure how to workaround that issue, but at least we would run properly again...

**Comment by mgedmin** [comment]
Perhaps we should open a `requests` issue asking for an API so we can do this?

**Comment by anarcat** [comment]
i thought https://github.com/shazow/urllib3/pull/257 and https://github.com/kennethreitz/requests/issues/1966 were the upstream issues, but feel free to open another one...

**Comment by mgedmin** [comment]
Ah, I didn't see the link to kennethreitz/requests#1966 before.

**Pull request merged**
